### PR TITLE
Fix grammar in readme

### PR DESCRIPTION
**Pull request by kmiyashiro**
`Markdown` is referring to the syntax, not an implementation.

### CODE REVIEW

**Comment by slinlee** [comment]
Sniped Eric

**Comment by epan** [comment]
> … “Markdown” is two things: (1) a plain text formatting syntax; and (2) a software tool, written in Perl, that converts the plain text formatting to HTML. See the Syntax page for details pertaining to Markdown’s formatting syntax. 

http://daringfireball.net/projects/markdown/

**Comment by kmiyashiro** [comment]
I think in this case it is a syntax. Fixed description.

**Comment by kmiyashiro** [comment]
Closing stale PRs.

**Pull request closed without merging**
